# Root Cargo.toml

[workspace]
members = [
    "chapter_10",
    "adder",
    "chapter_3_tests",
    "chapter_8_exercises",
    "chapter_13",
    "guessing_game",
    "chapter_4_tests",
    "chapter_15",
    "chapter_19",
    "hello_macro",
    "hello_macro_derive",
]
resolver = "2"
